// Shared constants for job positions and seeker profiles

export const JOB_CATEGORIES = [
  // Technology & Data (Group 1)
  ['Software Engineering', 1],
  ['Frontend Engineering', 1],
  ['Backend Engineering', 1],
  ['Full Stack Engineering', 1],
  ['Data Engineering', 1],
  ['Data Science & Machine Learning', 1],
  ['AI Engineering & Applied AI', 1],
  ['Analytics & Business Intelligence', 1],
  ['Cloud & DevOps', 1],
  ['Platform Engineering', 1],
  ['Site Reliability Engineering (SRE)', 1],
  ['Cybersecurity', 1],
  ['IT Infrastructure & Networking', 1],
  ['Systems Administration', 1],
  ['Database Administration', 1],
  ['QA & Test Engineering', 1],
  ['Mobile Development', 1],
  ['Game Development', 1],
  ['Embedded Systems Engineering', 1],

  // Product, Design & Project (Group 2)
  ['Product Management', 2],
  ['Technical Product Management', 2],
  ['Program & Project Management', 2],
  ['Agile Coaching & Scrum', 2],
  ['Product Operations', 2],
  ['UX / UI Design', 2],
  ['UX Research', 2],
  ['Service Design', 2],
  ['Design Operations', 2],

  // Business, Finance & Operations (Group 3)
  ['Business Operations', 3],
  ['Operations Management', 3],
  ['Business Analysis', 3],
  ['Strategy & Management Consulting', 3],
  ['Finance & Accounting', 3],
  ['Corporate Finance', 3],
  ['FP&A', 3],
  ['Risk, Compliance & Audit', 3],
  ['Supply Chain & Logistics', 3],
  ['Procurement & Vendor Management', 3],
  ['Process Improvement & Lean', 3],
  ['Enterprise Operations', 3],

  // Sales, Marketing & Revenue (Group 4)
  ['Sales (B2B / Enterprise)', 4],
  ['Sales (SMB / Mid-Market)', 4],
  ['Inside Sales', 4],
  ['Outside Sales', 4],
  ['Sales Engineering', 4],
  ['Sales Operations & Enablement', 4],
  ['Marketing (Brand & Content)', 4],
  ['Marketing (Performance & Growth)', 4],
  ['Demand Generation', 4],
  ['Lifecycle Marketing', 4],
  ['Product Marketing', 4],
  ['Customer Success', 4],
  ['Customer Support & Service', 4],
  ['Account Management', 4],
  ['Revenue Operations', 4],
  ['Business Development', 4],

  // People, Legal & Admin (Group 5)
  ['Human Resources & People Operations', 5],
  ['Talent Acquisition & Recruiting', 5],
  ['HR Business Partner', 5],
  ['Learning & Development', 5],
  ['Compensation & Benefits', 5],
  ['Legal & Contracts', 5],
  ['Paralegal & Legal Support', 5],
  ['Office Administration', 5],
  ['Executive Assistance', 5],
  ['Facilities Administration', 5],

  // Healthcare & Life Sciences (Group 6)
  ['Clinical Healthcare', 6],
  ['Registered Nurse (RN)', 6],
  ['Licensed Practical Nurse (LPN)', 6],
  ['Nurse Practitioner (NP)', 6],
  ['Physician & Surgeon', 6],
  ['Allied Health & Therapy Services', 6],
  ['Medical Imaging & Radiology', 6],
  ['Laboratory & Diagnostics', 6],
  ['Healthcare Administration', 6],
  ['Health Informatics & Analytics', 6],
  ['Biomedical Engineering', 6],
  ['Pharmaceuticals & Research', 6],
  ['Clinical Research & Trials', 6],
  ['Home Health & Caregiving', 6],

  // Creative, Media & Communications (Group 7)
  ['Creative & Visual Design', 7],
  ['Graphic Design', 7],
  ['Brand Design', 7],
  ['Motion Graphics & Animation', 7],
  ['Content Writing & Editing', 7],
  ['Copywriting', 7],
  ['Media Production (Video / Audio)', 7],
  ['Photography', 7],
  ['Public Relations & Communications', 7],
  ['Social Media & Community Management', 7],
  ['Influencer & Creator Management', 7],

  // Skilled Trades & Blue-Collar (Group 8)
  ['Electrician', 8],
  ['Plumber', 8],
  ['HVAC Technician', 8],
  ['Pipefitter', 8],
  ['Steamfitter', 8],
  ['Carpenter', 8],
  ['Concrete Finisher', 8],
  ['Welder & Fabricator', 8],
  ['Ironworker', 8],
  ['Machinist & CNC Operator', 8],
  ['Millwright', 8],
  ['Industrial Maintenance Technician', 8],
  ['Maintenance Mechanic', 8],
  ['Field Service Technician', 8],
  ['Heavy Equipment Operator', 8],
  ['Crane Operator', 8],
  ['Lineworker (Electrical / Utility)', 8],
  ['Mechanic (Auto / Diesel)', 8],
  ['Small Engine Mechanic', 8],
  ['Aviation Maintenance Technician', 8],
  ['Facilities Technician', 8],
  ['Elevator & Escalator Technician', 8],
  ['Boilermaker', 8],
  ['Tool & Die Maker', 8],
  ['Sheet Metal Worker', 8],
  ['Glazier', 8],
  ['Roofer', 8],
  ['Flooring Installer', 8],
  ['Painter (Commercial / Industrial)', 8],

  // Construction, Transportation & Field Operations (Group 9)
  ['Construction Management', 9],
  ['Site Supervisor & Foreman', 9],
  ['Estimator & Cost Control', 9],
  ['General Labor & Skilled Labor', 9],
  ['Commercial & Residential Construction', 9],
  ['Drywall & Framing', 9],
  ['Transportation & Truck Driving', 9],
  ['CDL Driver (Local / OTR)', 9],
  ['Delivery & Last-Mile Logistics', 9],
  ['Warehouse & Distribution', 9],
  ['Forklift & Equipment Operation', 9],
  ['Fleet Operations', 9],
  ['Logistics & Freight Operations', 9],
  ['Dispatch & Routing', 9],

  // Manufacturing, Energy & Utilities (Group 10)
  ['Manufacturing & Industrial Engineering', 10],
  ['Production & Assembly', 10],
  ['Machine Operator', 10],
  ['Quality Control & Inspection', 10],
  ['Process Technician', 10],
  ['Plant Operations', 10],
  ['Maintenance & Reliability', 10],
  ['Energy & Utilities', 10],
  ['Oil, Gas & Mining', 10],
  ['Refinery Operations', 10],
  ['Power Plant Operations', 10],
  ['Renewable Energy (Solar / Wind)', 10],
  ['Wind Turbine Technician', 10],
  ['Solar Installer', 10],
  ['Environmental, Health & Safety (EHS)', 10],
  ['Water & Wastewater Operations', 10],

  // Government, Education & Public Services (Group 11)
  ['Government & Public Sector', 11],
  ['Education & Training', 11],
  ['K–12 Teaching', 11],
  ['Higher Education Faculty', 11],
  ['Public Safety (Fire / Police / EMS)', 11],
  ['Corrections & Detention', 11],
  ['Military & Defense', 11],
  ['Veterans Services', 11],
  ['Nonprofit & Social Services', 11],
  ['Urban Planning & Public Works', 11]
];

export const EMPLOYMENT_TYPES = ['Full-time', 'Part-time', 'Contract', 'Temporary', 'Internship'];

export const WORK_SETTINGS = ['Remote', 'In-office', 'Hybrid', 'On-site'];

export const EDUCATION_LEVELS = ["High School", "Associate's", "Bachelor's", "Master's", "Doctorate", "None"];
